### ISSUE TITLE
debugger screenshot

### ISSUE THREAD

**Issue by the-Arioch** [scala-ide/docs#127]
"Input and tree on bottom" @ http://scala-ide.org/docs/current-user-doc/features/scaladebugger/expression-evaluator.html

http://scala-ide.org/docs/_images/input-and-tree-on-bottom1.png
http://scala-ide.org/docs/_images/input-and-tree-on-right1.png

same content

**Comment by sschaef** [comment]
\cc @Kwestor

**Comment by Kwestor** [comment]
Yay, it seems I did not paste my screenshot properly. I'll fix that on monday.

**Comment by mpociecha** [comment]
I corrected it during https://github.com/scala-ide/docs/pull/128

**Comment by Kwestor** [comment]
Fixed in #128

**Comment by the-Arioch** [comment]
quote: "Console and tree on right (defualt)"

de-WHAT ? :-P

On a serious note, maybe you would install some add-on script to make easy to reporting?  Select text, hit Ctrl+Enter or anything, and enter your complain

**Comment by sschaef** [comment]
I corrected the spelling mistake.

Isn't creating a Github issue already easy enough? I'm not sure if it is possible to make it even easier.

**Comment by the-Arioch** [comment]
It is,  AFTER you find it and create an account there. 

There is no official, published and suggested feedback channel, less so an easy to use instantly available one without preconditions with automatic collecting of relevant data (at very least the page and the quote). 

Basically i was going to put a bug on Scala compiler so someone would hopefully route the message. Then by chance i found this repo. 
Also i had an acc  here  due to a totally unrelated to Scala interests.
Would i have to register one i would probably just skip the hasstle.

-- 
Отправлено через К-9 Mail. Извините за краткость, пожалуйста.
